services:
  mysql:
    image: mysql:8.0
    container_name: benchmark_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: airline_benchmark
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: benchmark_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: